// Card art: keyword-mapped icons + shared artifacts for bounty option cards.
// Emoji lead badges/chips only (design.md) - never inside body sentences.
// First matching rule wins; order runs specific -> generic.

const ICON_RULES: [string, string][] = [
  ["marry", "💒"],
  ["wedding", "💒"],
  ["punch", "👊"],
  ["celestial dragon", "🐉"],
  ["burn", "🔥"],
  ["tesoro", "🎰"],
  ["casino", "🎰"],
  ["crocodile", "🐊"],
  ["kraken", "🐙"],
  ["octopus", "🐙"],
  ["shirahoshi", "🧜"],
  ["mermaid", "🧜"],
  ["saul", "🦣"],
  ["giant", "🦣"],
  ["loki", "🔨"],
  ["marry", "💒"],
  ["wedding", "💒"],
  ["steal", "🥷"],
  ["rob", "💰"],
  ["gold", "🪙"],
  ["bomb", "💣"],
  ["duel", "⚔️"],
  ["kill", "🗡️"],
  ["challenge", "⚔️"],
  ["read", "📖"],
  ["records", "📜"],
  ["glyph", "🗿"],
  ["library", "📚"],
  ["books", "📚"],
  ["drink", "🍺"],
  ["sail", "⛵"],
  ["ship", "🚢"],
  ["storm", "⛈️"],
  ["thunder", "⚡"],
  ["crown", "👑"],
  ["king", "👑"],
  ["ghost", "👻"],
  ["vanish", "👻"],
  ["hide", "🕵️"],
  ["stow", "🧳"],
  ["sea", "🌊"],
  ["geyser", "🌊"],
  ["island", "🏝️"],
  ["sky", "☁️"],
  ["moon", "🌙"],
  ["bell", "🔔"],
  ["sing", "🎵"],
  ["shout", "📢"],
  ["print", "📰"],
  ["whisper", "🤫"],
  ["bury", "⚰️"],
  ["trade", "🤝"],
  ["carve", "⛰️"],
  ["weapon", "💥"],
  ["map", "🗺️"],
  ["chain", "⛓️"],
  ["slave", "⛓️"],
  ["flag", "🏴‍☠️"],
  ["dragon", "🐉"],
  ["revolutionary", "💨"],
  ["marine", "⚓"],
  ["admiral", "⚓"],
  ["buggy", "🤡"],
  ["clown", "🤡"],
  ["temple", "⛩️"],
  ["vault", "🏦"],
  ["bet ", "🎲"],
  ["wager", "🎲"],
  ["poison", "☠️"],
  ["scaffold", "⚖️"],
  ["truth", "📜"],
];

export function iconFor(label: string): string {
  const lower = label.toLowerCase();
  for (const [keyword, icon] of ICON_RULES) {
    if (lower.includes(keyword)) return icon;
  }
  return "☠️";
}
